config/routes.rb
Rails.application.routes.draw do
  get 'stops/index'

  devise_for :users
  get 'from/where' => 'locations#new'
  get 'routes' => 'routes#index'
  get 'stops' => 'stops#index'
  root 'dashboards#index'

  resources :locations

  resources :dashboards

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  has_many :routes
  has_many :stops
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :connections
  has_many :stops, :through => :connections
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  has_many :connections
  has_many :routes, :through => :connections

  def get_routes_string
    route_strings = []
    self.connections.each do |r|
      begin
        route_strings << Route.find_by(id: r)['RouteID']
      rescue
        return '.'
      end
    end
    return route_strings.join(', ')
  end
  # 
  # def get_lat
  #   return self.lat
  # end
  #
  # def get_lon
  #   return self.lon
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dashboards
end

app/models/wmata.rb
# first of all kudos, but this is the kind of class that warrants a shit ton of
# comments. Lotsa cool stuff going on here as to what these different methods do
class Wmata
  include HTTParty
  base_uri 'https://api.wmata.com'
  # attr_reader :last_updated

  def initialize #(api_key)
    # @options = { query: { api_key: api_key} }
    @options = { query: { api_key: ENV['wmata_api_key']} }
  end

  def get_bus_routes
    response = self.class.get('/Bus.svc/json/jRoutes', @options)
    JSON.parse(response.body)['Routes']
  end

  def get_all_bus_stops
    response = self.class.get('/Bus.svc/json/jStops', @options)
    JSON.parse(response.body)['Stops']
  end

  def get_bus_stops(lat, lon, radius)
    # https://api.wmata.com/Bus.svc/json/jStops?Lat=38.878586&Lon=-76.989626&Radius=500
    uri_with_params = "https://api.wmata.com/Bus.svc/json/jStops?Lat=#{lat}&Lon=#{lon}&Radius=#{radius}"
    response = self.class.get(uri_with_params, @options)
    JSON.parse(response.body)['Stops']
  end

# how does this method definition differ from the one defined below it? I can see that
# you drill further into the body. I guess my biggest hangup is the naming of these two methods.
# providing an x in the second method doesn't provide any more semantic meaning
# If I'm another dev looking at this code, wouldn't really know what get_predictions does
# if get_predictions_x is drilling into a key of Predictions
  def get_predictions(stop_id)
    uri_with_params = "https://api.wmata.com/NextBusService.svc/json/jPredictions?StopID=#{stop_id}"
    response = self.class.get(uri_with_params, @options)
    JSON.parse(response.body)
  end

  def get_predictions_x(stop_id)
    uri_with_params = "https://api.wmata.com/NextBusService.svc/json/jPredictions?StopID=#{stop_id}"
    response = self.class.get(uri_with_params, @options)
    JSON.parse(response.body)['Predictions']
  end

  # def get_departure_times_for_ne3arby_bus_stops(lat, lon, radius)
  #   bus_stops = self.get_bus_stops(lat, lon, radius)
  #   bus_stops.each do |stop|
  #     s = stop['StopID']
  #     stop.merge!('Predictions': self.get_predictions_x(s))
      # stop.merge!(self.get_predictions(s))
  #   end
  #   return bus_stops
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # i can't see if you have error handling and rescue from exceptions somewhere else.
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @my_dashboards = []
    if current_user
      @my_dashboards = current_user.dashboards
      not_mine = Dashboard.where.not(user_id: current_user.id)
      @dashboards = not_mine.where(public: true)
    else
      @dashboards = Dashboard.where(public: true)
    end
  end

  def show
    @dashboard = Dashboard.find(params[:id])
    stop_ids = @dashboard.stop_id_str.strip.split
    @predictions = []
    @stops = []
    stop_ids.each do |stop|
      # @predictions << Wmata.new(ENV['wmata_api_key']).get_predictions(stop)
      @predictions << Wmata.new.get_predictions(stop)
      @stops << Stop.find_by('StopID' => stop)
    end
  end

  def new
    # @lat = 38.9049836
    # @lon =  -77.0336719
    @dashboard = Dashboard.new
    @stops = Wmata.new.get_bus_stops(38.9049836, -77.0336719, 500)


  end

  def edit
    @dashboard = Dashboard.find(params[:id])
    # stop_ids = @dashboard.stop_id_str.strip.split
    # # @stops = Wmata.new.get_bus_stops(@dashboard.lat, @dashboard.lon, 400)
    # @stops = []
    # stop_ids.each do |stop|
    #   # @predictions << Wmata.new.get_predictions(stop)
    #   @stops << Stop.find_by('StopID': stop)
    # end
    @stops = Wmata.new.get_bus_stops(@dashboard.lat, @dashboard.lon, 500)
  end

  def create
    dashboard = Dashboard.new(dashboard_params.merge(user: current_user))
    if dashboard.save
      #notice?
      redirect_to dashboard
    else
      render 'new'
    end
  end

  def update
    dashboard = Dashboard.find(params[:id])
    if dashboard.update(dashboard_params)
      #could this generate a 'notice'?
      redirect_to dashboard_path(dashboard)
    else
      render 'edit'
    end
  end

  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy
    redirect_to dashboards_path
  end

  private
    def dashboard_params
      params.require(:dashboard).permit(:title, :address, :desc, :public, :lat, :lon, :stop_id_str)
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all

    @route_attributes = ['RouteID', 'Name', 'LineDescription']
    # @routes = Wmata.new(ENV['wmata_api_key']).get_bus_routes
    @routes = Wmata.new.get_bus_routes
  end

  def new # get user's location, mapped to from/where
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.save
    redirect_to @location
  end

  def show
    # this is great, but seems like a lot of logic happening in the controller.
    # What I would do is abstract this functionality and create a Prediction model.
    # A PORO(plain old ruby object) would do nicely here since we aren't inheriting from AR for this.
    # But the prediction model should do the functionality here instead of having alot of your business logic in the controller
    @location = Location.find(params[:id])
    # @stop_attributes = ['StopID', 'Name', 'Lon', 'Lat', 'Routes']
    # stops = Wmata.new(ENV['wmata_api_key']).get_bus_stops(@location.lat, @location.lon, 300)
    stops = Wmata.new.get_bus_stops(@location.lat, @location.lon, 300)
    stop_ids = []
    stops.each do |s|
      stop_ids << s['StopID']
    end
    @stops = stop_ids.join(', ')
    # puts stops.inspect
    @predictions = []
    stops.each do |stop|
      # @predictions << Wmata.new(ENV['wmata_api_key']).get_predictions(stop['StopID'])
      @predictions << Wmata.new.get_predictions(stop['StopID'])
    end # why does this nest like this?

  end

  private
    def location_params
      params.require(:location).permit(:lat, :lon)
    end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  def index
    @route_attributes = ['LineDescription', 'Name', 'RouteID']
    @routes = Route.all
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController

  def index
    @stops = Stop.all[0..20]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/dashboards/_form.html.haml
.form
  .card
    = form_for @dashboard, :html => {:class => "col s12 card-content"} do |f|
      .row
        - if @dashboard.errors.any?
          #error_explanation
            %h3
              = pluralize(@dashboard.errors.count, "error")
              prohibited this dashboard from being saved:
            %ul
              - @dashboard.errors.full_messages.each do |msg|
                %li= msg
      .row
        .input-field.col.s9
          %i.material-icons.prefix mode_edit
          = f.label :title, 'title of dashboard'
          = f.text_field :title, :placeholder => 'e.g. Acme Corp. HQ'
        .input-field.col.s3
          = f.check_box :public #, :class => 'filled-in'
          = f.label :public, 'make public'
      .row
        .input-field.col.s12
          %i.material-icons.prefix mode_edit
          = f.label :address
          = f.text_field :address, :placeholder => 'e.g. 1600 Penn. Ave NW'
      .row
        .input-field.col.s12
          %i.material-icons.prefix mode_edit
          = f.label :desc
          = f.text_field :desc #, :placeholder => 'e.g. some motto'
      .row
        .input-field.col.s6
          = f.label :lat, 'latitude'
          = f.text_field :lat #, class: 'lat'
        .input-field.col.s6
          = f.label :lon, 'longitude'
          = f.text_field :lon #, class: 'lon'
      .row.hide
        .input-field.col.s12.hide
          = f.label :stop_id_str
          = f.text_field :stop_id_str
      .row
        = f.submit nil, :class => 'btn waves-effect waves-light'

app/views/dashboards/_map.html.haml
-# .map_content_container.card.container
-#   .sidebar.not_displayed
-#     .heading
-#     %h3 Bus stops
-#     #listings.listings
#map.container
-# :javascript
-#   // L.mapbox.accessToken = 'pk.eyJ1IjoibW9vbmlrZXIiLCJhIjoiY2loNHkwMmUwMHp1Znc5bTVxZGptZ3d1eSJ9.IjtdkC-4egUXjw39mKShgA';
-#   // var map = L.mapbox.map('map', 'mapbox.pirates')
-#   //    .setView([38.9048, -77.03387], 15);
-#   // L.control.fullscreen().addTo(map);
-#
-#   $(document).ready(function () {
-#
-#     function makeMap (lat, lon) {
-#       L.mapbox.accessToken = 'pk.eyJ1IjoibW9vbmlrZXIiLCJhIjoiY2loNHkwMmUwMHp1Znc5bTVxZGptZ3d1eSJ9.IjtdkC-4egUXjw39mKShgA';
-#       var map = L.mapbox.map('map', 'mapbox.pirates')
-#           .setView([lat, lon], 16);
-#
-#       // L.marker is a low-level marker constructor in Leaflet.
-#       L.marker([lat, lon], {
-#           icon: L.mapbox.marker.icon({
-#               'marker-size': 'large',
-#               'marker-symbol': 'building',
-#               'marker-color': '#fa0'
-#           })
-#       }).addTo(map);
-#
-#       // for each bus stop on dashboard, display it
-#       var stops = [];
-#       $('.bus_stop_data').each( function (index, value) {
-#         var stop = $(this).children();
-#         var s = {};
-#         s.name = stop.eq(0).text();
-#         s.id = stop.eq(1).text();
-#         s.lat = stop.eq(2).text();
-#         s.lon = stop.eq(3).text();
-#         stops.push(s);
-#       });
-#
-#       stops.forEach ( function (stop) {
-#         L.marker([stop.lat, stop.lon], {
-#             icon: L.mapbox.marker.icon({
-#                 'marker-size': 'large',
-#                 'marker-symbol': 'bus',
-#                 'marker-color': '#fa0'
-#             })
-#         }).addTo(map);
-#       });
-#     }
-#
-#     if ( $('#lat').length != 0 && $('lon') != 0 ) {
-#       var lat = parseFloat( $('#lat').text() );
-#       var lon = parseFloat( $('#lon').text() );
-#       makeMap( lat, lon );
-#       // console.log('Map generated');
-#     } else if ( $('#dashboard_lat').length == 1 && $('#dashboard_lon').length == 1 ) {
-#       var lat = parseFloat( $('#dashboard_lat').val() );
-#       var lon = parseFloat( $('#dashboard_lon').val() );
-#       // console.log('Map generated from form');
-#       makeMap( lat, lon );
-#     } // else {
-#     //  console.log('Map not generated');
-#     // }
-#   });

app/views/dashboards/_stops_info.html.haml
#stops_info.card.not_displayed
  %h3 Bus Stop Info
  %ul
    - @stops.each do |stop|
      %li.bus_stop_data
        - if stop != nil
          %span.stop_name= stop['Name'] #.titleize
          %span.stop_id= stop['StopID']
          %span.stop_lat= stop['Lat']
          %span.stop_lon= stop['Lon']

app/views/dashboards/edit.html.haml
%h2 Edit Dashboard?
= render 'stops_info'
= render 'map'
= render 'form'
= link_to 'Delete', dashboard_path(@dashboard), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn waves-effect waves-light'
= link_to 'Cancel', dashboards_path, :class => 'btn waves-effect waves-light'

app/views/dashboards/index.html.haml
.row
  .col.s12.m6
    .card
      .card-content
        - if @my_dashboards
          - if @my_dashboards.length != 0
            %ul.collection.with-header
              %li.collection-header
                %h4 Your Dashboards
              - @my_dashboards.each do |dash|
                %li.collection-item
                  %div
                    = link_to dash.title, dash
                    = link_to dashboard_path(dash), method: :delete, data: { confirm: 'Are you sure?' }, class: 'secondary-content' do
                      %i.material-icons.small delete
                    = link_to edit_dashboard_path(dash), class: 'secondary-content' do
                      %i.material-icons.small edit
          - else
            %p You don't have any dashboards yet.
  .col.s12.m6
    .card
      .card-content
        - if @dashboards
          %ul.collection.with-header
            %li.collection-header
              %h4 Everyone's Dashboards
            - @dashboards.each do |dash|
              %li.collection-item
                %div
                  = link_to dash.title, dash
        - else
          %p No public dashboards are available yet.

app/views/dashboards/new.html.haml
%h2 New Dashboard?
= render 'form'
= render 'stops_info'
= render 'map'
= link_to 'Cancel', dashboards_path, :class => 'btn waves-effect waves-light'

app/views/dashboards/show.html.haml
#dashboard_header
  %h2= @dashboard.title
  %p= @dashboard.desc
  %p#lat.not_displayed.hide= @dashboard.lat
  %p#lon.not_displayed.hide= @dashboard.lon
  -# %p= @dashboard.user_id
  -# %p= "Viewing Arrival Times for These Stop #s: #{@dashboard.stop_id_str}"
  - if @dashboard.user_id == current_user.id
    %i.material-icons.small= link_to 'edit', edit_dashboard_path(@dashboard)
    %i.material-icons.small= link_to 'delete', dashboard_path(@dashboard), method: :delete, data: { confirm: 'Are you sure?' }
= render 'stops_info'
-# = render 'map'
- @predictions.each do |stop|
  .bus_stop_card.card.hoverable
    .card-content
      - if stop['Predictions'].length == 0
        %span.card-title= "No predictions for #{stop['StopName']}"
      - else
        %span.card-title= "#{stop['StopName']}"
        %table.striped.responsive-table
          %thead
            %tr
              %th.center-align Minutes
              %th.center-align RouteID
              %th.center-align DirectionText
              -# %th DirectionNum
              -# %th VehicleID
              -# %th TripID
          %tbody
            - stop['Predictions'].each do |p|
              %tr
                %td.center-align= p['Minutes']
                %td.center-align= p['RouteID']
                %td.center-align= p['DirectionText']
                -# %td= p['DirectionNum']
                -# %td= p['VehicleID']
                -# %td= p['TripID']

app/views/layouts/application.html.haml
/ Wow haml.. i have no words, except, you suck.... haha no jk. How do you like haml?
/ I don't know much about it, but looking at your code base has taught me alot about it! Seems cool!
/ wedding wire uses haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OMW (wmata bus arrival/departure dashboards)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:content => "initial-scale=1,maximum-scale=1,user-scalable=no", :name => "viewport"}/
    %script{:src => "https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.js"}
    %script{:src => "https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v0.0.4/Leaflet.fullscreen.min.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/v2.2.3/mapbox.css", :rel => "stylesheet"}/
    %link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v0.0.4/leaflet.fullscreen.css", :rel => "stylesheet"}
    / Compiled and minified CSS
    -# %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css", :rel => "stylesheet"}/
    -# / Compiled and minified JavaScript
    -# %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"}
    / Import Google Icon Font
    %link{:href => "http://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
  %body.teal.darken-2
    .container
      %header
        #output
        %p#notice.notice= notice
        %p#alert.alert= alert
        %ul#account-dropdown.dropdown-content
          - if user_signed_in?
            %li= link_to 'settings', edit_user_registration_path
            %li= link_to 'log out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'sign up', new_user_registration_path
            %li= link_to 'log in', new_user_session_path
        %ul#dash-dropdown.dropdown-content
          %li= link_to 'browse dashboards', dashboards_path
          - if user_signed_in?
            %li= link_to 'create new dashboard', new_dashboard_path
        %nav.indigo.darken-4
          .nav-wrapper
            = link_to 'OMW', root_path, class: 'brand-logo'
            %ul#nav-mobile.right.hide-on-medium-and-down
              - if user_signed_in?
                -# dropdown triggers
                %li
                  %a(class="dropdown-button" href="#!" data-activates="dash-dropdown") dashboards
                %li
                  %a(class="dropdown-button" href="#!" data-activates="account-dropdown")= current_user.email
      .main
        = yield

app/views/locations/_stop.html.haml
.bus_stop
  %h3.name
    = stop['Name']
    = stop['StopID']
    -# = stop['Lat']
    -# = stop['Lon']
  %table
    %thead
      %tr
        %th min
        %th route
        %th to where
    %tbody
      - stop[:Predictions].each do |p|
        %tr
          %td= p['Minutes']
          %td= p['RouteID']
          %td= p['DirectionText']

app/views/locations/index.html.haml
%h2 Location#index (listing of location requests)
%ul
  - @locations.each do |location|
    %li= link_to "#{location.lat}, #{location.lon}", location
%h2 Routes
%table
  %thead
    %tr
      - @route_attributes.each do |attribute|
        %th= attribute
  %tbody
  - @routes.each do |route|
    %tr
      - @route_attributes.each do |attribute|
        %td= route[attribute]

app/views/locations/new.html.haml
%h2 Location#new
%p Where are you?
%div{ onclick: "geoFindMe()"} Click Me
#out
.map_container
  #map
  :javascript
    L.mapbox.accessToken = 'pk.eyJ1IjoibW9vbmlrZXIiLCJhIjoiY2loNHkwMmUwMHp1Znc5bTVxZGptZ3d1eSJ9.IjtdkC-4egUXjw39mKShgA';
    var map = L.mapbox.map('map', 'mapbox.pirates')
        .setView([38.9048, -77.03387], 15);
    L.control.fullscreen().addTo(map);
= form_for(@location, method: 'post') do |f|
  .board_form
    = f.text_field :lat
    = f.text_field :lon
    = f.submit

app/views/locations/show.html.haml
%h3 Location#show
%p
  = @location.lat
  = @location.lon
  = @stops

-# = render partial: 'stop', collection: @stops

- @predictions.each do |stop|
  .bus_stop_card
    %h3= "#{stop['StopName']}"
    %table
      %thead
        %tr
          %th Minutes
          %th RouteID
          %th DirectionText
          -# %th DirectionNum
          %th VehicleID
          %th TripID
      %tbody
        - stop['Predictions'].each do |p|
          %tr
            %td= p['Minutes']
            %td= p['RouteID']
            %td= p['DirectionText']
            -# %td= p['DirectionNum']
            %td= p['VehicleID']
            %td= p['TripID']

app/views/routes/index.html.haml
%h2 Bus Routes
%table
  %thead
    %tr
      - @route_attributes.each do |attr|
        %th= attr
  %tbody
    - @routes.each do |r|
      %tr
        - @route_attributes.each do |attr|
          %td= r[attr]

app/views/stops/index.html.haml
%h2 Bus Stops
%table
  %thead
    %tr
      %th Lat
      %th Long
      %th StopID
      %th Name
      %th Routes
  %tbody
    - @stops.each do |s|
      %tr
        %td= s['Lat']
        %td= s['Lon']
        %td= s['StopID']
        %td= s['Name']
        %td= s.get_routes_string